# Generated by Django 2.2 on 2020-07-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('Name', models.CharField(max_length=45)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=500)),
            ],
        ),
    ]
