# Generated by Django 2.2 on 2020-08-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('verify_email', models.EmailField(max_length=50)),
                ('text', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='classes',
        ),
    ]
