# Generated by Django 2.2 on 2020-08-07 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_App', '0002_auto_20200806_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
